name: Deploy Site

on:
  push:

jobs:
  publish:
    name: Publish Site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repo

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: yarn
        name: Install Dependencies

      - run: yarn build
        name: Build Site

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: werkkasten # e.g. 'my-project'
          directory: build # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}